name: comp_cert_tacminer
num_files: 1 
language: COQ
few_shot_data_path_for_retrieval: #.log/tools/coq_raw_proofs/data/benchmarks/CompCert/2023-09-06-03-44-06/CompCert/train
few_shot_metadata_filename_for_retrieval: #single.meta.json
dfs_data_path_for_retrieval: #.log/run_data_generation_transforms/data/benchmarks/CompCert/train
dfs_metadata_filename_for_retrieval: #local.meta.json
datasets:
  - project: ../raw-data/CompCert
    files:
      - path: backend/NeedDomain_comp_TM.v
        theorems:
          - lessdef_vagree_list   
          - vagree_lessdef_list   
          - iagree_not           
          - iagree_or           
          - andimm_sound      
          - orimm_sound        
          - sub_sound        
          - modarith_idem   