name: coq_art_peano
num_files: 1
language: COQ
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  - project: ../raw-data/coq-art
    files:
      - path: chap5_comp_PN.v
        theorems:
          - contrap 
          - conv_example
          - ex_imp_ex
          - imp_trans
          - le_mult_mult