name: coq_art
num_files: 1
language: COQ
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  # - project: data/benchmarks/coq-art
  - project: ../raw-data/coq-art
    files:
      - path: chap11.v
        theorems:
          - RM_1 
          - rmax_7
          - min_not_occ 
          - not_right 
          - rmax_6
          - go_right
      - path: chap5.v
        theorems:
          - contrap # custom1
          - conv_example # custom2 (0. 1. 1)
          - ex_imp_ex # custom0
          - imp_trans # custom0
          - le_mult_mult # custom0
      #     # - lt_8_9 # custom1
      #     # - lt_S # custom0
      #     # - mult_le_compat_r # custom0
      #     # - my_I # custom2
      - path: parsing.v
        theorems:
          - bin_to_string_wp # custom13, custom23 (0. 0. 0)
          - wp_o_head_c # custom7 (1. 1. 1)
          - wp_o_tail_c # custom7 (0. 0. 0)
      - path: impredicative.v
        theorems:
          - impredicative_le_n # custom2 (0. 1. 1)
          - impredicative_sorted_to_sorted # custom3 (1. 1. 1)
          - isorted1 # custom2 (0. 1. 1)
          - isorted2 # custom3 (1. 0. 0)