name: coq_art_tacminer
num_files: 1
language: COQ
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  - project: ../raw-data/coq-art
    files:
      - path: impredicative_comp_TM.v
        theorems:
          - impredicative_le_n 
          - impredicative_sorted_to_sorted 
          - isorted1 
          - isorted2 