
name: optimization 
num_files: 1
language: COQ
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  - project: data/benchmarks/optimization
    files:
      # - path: autolifter_single_pass_0after1.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_0s1s.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_atoi.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_cn1s.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_dropwhile.v
      #   theorems: 
      #     - optimize
      - path: autolifter_single_pass_length.v
        theorems: 
          - optimize
      # - path: autolifter_single_pass_longest1s.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_max_dist_between_zeros.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_max_len_1s.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_mis.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_mps.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_mts.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_pass_sum.v
      #   theorems: 
      #     - optimize
      # - path: autolifter_single_passcount10p.v
      #   theorems: 
      #     - optimize
      # - path: fusion_algprog_ex3_13.v
      #   theorems: 
      #     - optimize
      # - path: fusion_algprog_ex3_14.v
      #   theorems: 
      #     - optimize