name: Znumbertheory_nl
num_files: 1
language: COQ
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  - project: data/benchmarks/coq
    files:
      - path: theories/ZArith/Znumbertheory_nl.v 
        theorems: 
          - mod_fib
          # - fib_nat
          # - split2
          # - G_induct_3
          # - mod3_0_impl
          # - case1
          # - random_name
          # - Zdivide_dec0
          # - Zdivide_dec1
          # - Zdivide_dec
          # - Zdivide_Zdiv_eq_2
          # - Zdivide_Zdiv_lt_pos
          # - Zmod_div_mod
          # - Zmod_divide_minus
          # - Zdivide_mod_minus
          # - rel_prime_mult

          # - euclid_rec
          # - euclid
          # - Zis_gcd_bezout
          # - Zis_gcd_mult